FROM python:3.9-slim-buster

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ../1_creating_the_user_application/ .

CMD [ "python", "user_app.py" ]